services:
  front:
    # build: ../../front
    image: ghcr.io/limits1214/tetris-front:latest
    container_name: tetris-front
    # restart: always
    networks:
      - shared

  back-api:
    # build:
    #   context: ../../back
    #   dockerfile: api/Dockerfile
    image: ghcr.io/limits1214/tetris-back-api:latest
    container_name: tetris-back-api
    environment:
      ENV__REDIS__REDIS_URL: ${REDIS_URL}
      ENV__DATABASE__DATABASE_URL: ${DATABASE_URL}
    # restart: always
    volumes:
      - ${VOL_MOUNT_PATH}/tetris-app-docker-volume/back-api/logs:/app/logs
    networks:
      - shared

  back-ws:
    # build:
    #   context: ../../back
    #   dockerfile: api/Dockerfile
    image: ghcr.io/limits1214/tetris-back-ws:latest
    container_name: tetris-back-ws
    environment:
      ENV__REDIS__REDIS_URL: ${REDIS_URL}
      ENV__DATABASE__DATABASE_URL: ${DATABASE_URL}
    # restart: always
    volumes:
      - ${VOL_MOUNT_PATH}/tetris-app-docker-volume/back-ws/logs:/app/logs
    networks:
      - shared

networks:
  shared:
    name: tetris-shared-net
    external: true
