name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  ghpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          cargo install wasm-pack

          chmod +x back/tetris-lib/wasm_pkg_build.bash
          chmod +x front/build_docker_front.bash

          cd back/tetris-lib
          ./wasm_pkg_build.bash
          cd ../..

          cd front
          ./build_docker_front.bash
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/build

  build-docker-image:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04-arm

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #   - name: Set up QEMU
      #     uses: docker/setup-qemu-action@v3
      #     with:
      #       platforms: all

      #   - name: Set up Docker Buildx
      #     uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          cargo install wasm-pack

          chmod +x back/tetris-lib/wasm_pkg_build.bash
          chmod +x front/build_docker_front.bash
          chmod +x back/build_docker_api.bash
          chmod +x back/build_docker_ws.bash

          cd back/tetris-lib
          ./wasm_pkg_build.bash
          cd ../..

          cd front
          ./build_docker_front.bash
          cd ..

          cd back
          ./build_docker_api.bash
          ./build_docker_ws.bash
